default_language_version:
  python: python3.10
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    language_version: python3
- repo: https://github.com/psf/black
  rev: 24.3.0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    # Override default --ignore-missing-imports
    args: []
    additional_dependencies:
    - sqlalchemy2-stubs
    - pydantic
    - sqlalchemy
    - httpx
    - fastapi
    - pytest
    - types-itsdangerous
