channels:
  - conda-forge
dependencies:
  - pytest >=7.1.0
  - pytest-cov
  - pre-commit
  - black
  - flake8
  - isort
  - ipython >=8.0  # useful for debugging asyncio code
  - sqlalchemy2-stubs
  - mypy
category: dev
